#!/bin/sh

set -eu

fullscreen=0
transcode=1
audio=0
while getopts 'fan' o; do
    case $o in
        f) fullscreen=1 ;;
        a) audio=1 ;;
        n) transcode=0 ;;
    esac
done
shift $((OPTIND-1))

if [ $# -ne 1 ]; then
    echo "Usage: $0 <base_name>" 1>&2
    exit 1
fi

base_name=$1
base_cmd="ffmpeg -f x11grab -show_region 1 -draw_mouse 1 -r 60"
ofile="$base_name.mp4"

if [ $fullscreen -eq 1 ]; then
    cmd="$base_cmd -s \$(xrandr | grep '*' | awk '{ print \$1 }') -i :0.0"
else
    cmd="$base_cmd \$(slop -f '-s %wx%h -i :0.0+%x,%y')"
fi

if [ $audio -eq 1 ]; then
    cmd="$cmd -f pulse -ac 2 -i 48"
fi

cmd="$cmd -preset ultrafast -qp 0"  # x264 lossless

if [ $transcode -eq 0 ]; then
    eval "$cmd" "$ofile"
else
    tmpfile="tmp_$base_name.mp4"
    eval "$cmd" "$tmpfile"

    # cropping for non power of 2 selections
    cmd="ffmpeg -i $tmpfile -vf 'crop=trunc(iw/2)*2:trunc(ih/2)*2' -pix_fmt yuv420p $ofile"
    eval "$cmd"
    rm -f "$tmpfile"
fi

echo "Record: $ofile"
