#!/bin/zsh

set -eu

. "$(dirname "$0")/config"

while getopts 'd:es' o; do
    case $o in
        d) delay=$OPTARG ;;
        e) editor=$SHOT_EDITOR ;;
        s) sel=$(slop -f "-i %i -g %g")
           test -z $sel && exit 1
           ;;
    esac
done
shift $((OPTIND-1))
f=${1:-$(date +%F-%H%M%S)-$(pwgen).png}
test -z ${delay:-} || sleep $delay
shotgun ${=sel:-} $f && echo $f
test -z ${editor:-} || $editor $f
